
- name: postgres | install postgresql
  apt: pkg={{item}} state=installed update_cache=yes
  with_items:
    - postgresql
    - postgresql-contrib
  notify:
    - restart postgresql
  become: yes

# - block:
#   - name: postgres | add dspace user
#     postgresql_user: name={{dspace_db_user}} password={{dspace_db_pass}}
#     tags: postgres
# 
#   - name: postgres | add dspace database
#     postgresql_db: name={{dspace_db_name}} encoding='UTF-8' template='template0' owner={{dspace_db_user}}
#     tags: postgres
#     
#   - name: Install pgcrypto extension
#     postgresql_ext:
#       name: pgcrypto
#       db: '{{dspace_db_name}}'
# 
#   - name: postgres | configure md5 auth for dspace database
#     template: src=pg_hba.conf.j2 dest=/etc/postgresql/9.5/main/pg_hba.conf
#     notify:
#       - restart postgresql
#     tags: postgres
#   become: yes
#   become_user: postgres
