version: "2"
services:
  postgres:
    environment:
      MYSQL_DATABASE: vufind
      MYSQL_USER: vufind 
      MYSQL_PASSWORD: vufind
      MYSQL_ROOT_PASSWORD: root
    image: ubuntu:xenial
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/src:/srv/dspace/src
    command: /bin/bash
  dspace:
    image: ubuntu:xenial
    ports:
      - 8080:8080
    links:
      - postgres
    command: /bin/bash

registries: {}
  # Add optional registries used for deployment. For example:
  #  google:
  #    url: https://gcr.io
  #    namespace: my-cool-project-xxxxxx   